#!/bin/bash

CC	= mpiCC
CFLAGS	= -Wall -Wextra

HEADER_PATH_MUI	= -I../../../mui

LDFLAGS = -lstdc++ -fpermissive

SCR = $(wildcard *.cpp)
EXE = $(SCR:.cpp=)

all: $(EXE)

% : %.cpp
	$(CC) $(CFLAGS) $(HEADER_PATH_MUI) $< -o $@ $(LDFLAGS)

.PHONY: clean
	
clean:
	-rm -f $(EXE) *.txt
